version: '3.7'

services:
  dind-master:
    image: docker
    command: ["docker","stack","deploy","--compose-file","/vagrant/SampleStack/swarm/docker-compose.yml","web"]
    volumes:
      - type: bind
        source : /var/run/docker.sock
        target : /var/run/docker.sock
      - type: bind
        source : /vagrant
        target : /vagrant
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

