---
- hosts: all
  become: yes
  tasks:
  - name: Docker deb packages
    apt: name={{item}} state=present
    with_items:
    - docker.io
  - name: Adding vagrant to docker user 
    user: name=vagrant
          group=docker
          append=yes
  - name: Start docker
    systemd:
      state: started
      name: docker